apiVersion: v1
kind: Service
metadata:
  name: msme-frontend
  labels:
    app.kubernetes.io/name: msme-frontend
    app.kubernetes.io/part-of: msme-marketplace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: msme-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
